// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcjPUuETpOf1xPBoGoLj33zgzVPnB2rTI',
    appId: '1:733154199984:web:878f4d94b208560aa3ee75',
    messagingSenderId: '733154199984',
    projectId: 'sigizi',
    authDomain: 'sigizi.firebaseapp.com',
    storageBucket: 'sigizi.firebasestorage.app',
    measurementId: 'G-8EB52HX41S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuzec3Q3ct16JwBXndC1bNy3azz-YIyVE',
    appId: '1:733154199984:android:5baec11f2af308d7a3ee75',
    messagingSenderId: '733154199984',
    projectId: 'sigizi',
    storageBucket: 'sigizi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvUtWqi6kTy06fAs2nX5ymHcVCqHpmfHs',
    appId: '1:733154199984:ios:14f109e87f8e24a2a3ee75',
    messagingSenderId: '733154199984',
    projectId: 'sigizi',
    storageBucket: 'sigizi.firebasestorage.app',
    iosBundleId: 'com.example.sigizi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvUtWqi6kTy06fAs2nX5ymHcVCqHpmfHs',
    appId: '1:733154199984:ios:14f109e87f8e24a2a3ee75',
    messagingSenderId: '733154199984',
    projectId: 'sigizi',
    storageBucket: 'sigizi.firebasestorage.app',
    iosBundleId: 'com.example.sigizi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcjPUuETpOf1xPBoGoLj33zgzVPnB2rTI',
    appId: '1:733154199984:web:1e76b5f0b1445f98a3ee75',
    messagingSenderId: '733154199984',
    projectId: 'sigizi',
    authDomain: 'sigizi.firebaseapp.com',
    storageBucket: 'sigizi.firebasestorage.app',
    measurementId: 'G-CZXF8FKLEP',
  );
}
